### GET ALL 
GET http://localhost:5000/entries/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR6WE83d0F3RXNESmVUQ21NWHpNaXN1UDU0d2dXZjliSHg3dXRSMWJ2blhkZ1lITkhkUEZsNiIsImlhdCI6MTcyNjA2NjAzOSwiZXhwIjoxNzI2MTUyNDM5fQ.1_kq-5Rob_b38JM72AjHQ14M9w8n17eabpDetqHdvvc"
}


### GET BY SEARCH
GET http://localhost:5000/entries/search?dateb=1726002930002
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR6WE83d0F3RXNESmVUQ21NWHpNaXN1UDU0d2dXZjliSHg3dXRSMWJ2blhkZ1lITkhkUEZsNiIsImlhdCI6MTcyNjA2NjAzOSwiZXhwIjoxNzI2MTUyNDM5fQ.1_kq-5Rob_b38JM72AjHQ14M9w8n17eabpDetqHdvvc"
}

### CREATE ONE
POST http://localhost:5000/entries
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR6WE83d0F3RXNESmVUQ21NWHpNaXN1UDU0d2dXZjliSHg3dXRSMWJ2blhkZ1lITkhkUEZsNiIsImlhdCI6MTcyNjA2NjAzOSwiZXhwIjoxNzI2MTUyNDM5fQ.1_kq-5Rob_b38JM72AjHQ14M9w8n17eabpDetqHdvvc",
    "title": "My first entry",
    "content": "This is my first entry in my journal"
}

### UPDATE ONE
PATCH  http://localhost:5000/entries/ca4221dc-9b82-430f-b231-705565aabbfb
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR6WE83d0F3RXNESmVUQ21NWHpNaXN1UDU0d2dXZjliSHg3dXRSMWJ2blhkZ1lITkhkUEZsNiIsImlhdCI6MTcyNjA2NjAzOSwiZXhwIjoxNzI2MTUyNDM5fQ.1_kq-5Rob_b38JM72AjHQ14M9w8n17eabpDetqHdvvc",
    "mood": "Happy",
    "tags": ["personal", "journal"]
}

### DELETE ONE
DELETE http://localhost:5000/entries/356f9634-3597-4dd1-ada5-e0f6da0fc360
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCR6WE83d0F3RXNESmVUQ21NWHpNaXN1UDU0d2dXZjliSHg3dXRSMWJ2blhkZ1lITkhkUEZsNiIsImlhdCI6MTcyNjA2NjAzOSwiZXhwIjoxNzI2MTUyNDM5fQ.1_kq-5Rob_b38JM72AjHQ14M9w8n17eabpDetqHdvvc"
}