### LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "@passworD123"
}

### REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "@passworD123"
}


# ### GET ALL (ONLY FOR DEV)
# GET http://localhost:5000/dev