### GET AN USER
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "ruizigor16@gmail.com",
    "password": "@12Mara12"
}

### CREATE AN USER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "ruizigor16@gmail.com",
    "password": "@12Maria12"
}

